[package]
name = "alpha_test"
version = "0.1.0"
edition = "2024"

[dependencies]
#libc = { version = "0.2", default-features = false }
#alloc = { package = "alloc", version = "*", optional = true } # ignore if not needed
